### ISSUE TITLE
Error when trying to access prescriptions without permissions (and then I can click a prescription...)

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2377]
## What went wrong? 😲
 
I get an error when trying to access the prescriptions window as the Admin user on the demo server: 

![Screen Shot 2023-10-17 at 3 17 06 PM](https://github.com/openmsupply/open-msupply/assets/29744386/c123102b-79d2-4eed-9918-bd628ba3f4dc)

The weird part is that I can still click into it: 

https://github.com/openmsupply/open-msupply/assets/29744386/11149f74-5035-40cb-a1d7-d939bc8a721b

(Can't tell if that is a second bug at the end of that video - why is it giving me an error saying Number of packs below 1? also would be good to be human readable (or at least nice for humans to read) 

## Expected behaviour 🤔
If I don't have permission, it shouldn't let me click into everything...

But also, it looks like I __do__ have permissions; 
<img width="819" alt="image" src="https://github.com/openmsupply/open-msupply/assets/29744386/505a7934-755f-4ffb-a3b3-fdce6d9903df">

Am I looking at the right place?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On the demo server, log into a dispensary store 
2. Click on prescriptions 
3. See the error, click ok and continue clicking 

## Your environment 🌱

 - Version: 1.4.0 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [x] desktop (macOS) demo server 
   - [ ] server (windows)

**Comment by mark-prins** [comment]
Fixed - the Admin user did not have `PATIENT_QUERY` permission for that store. I've manually added it

**Comment by DhanyaHerath** [comment]
@mark-prins Oooh, is that a migration problem? Will we have to do that for every time we upgrade? Or just this case

**Comment by roxy-dao** [comment]
The `Search by name` filter requires the `PATIENT_QUERY` permission... which is the same as with Customer/Supplier filter... Can we close this issue? 🤔

**Comment by DhanyaHerath** [comment]
@roxy-dao happy for this issue to be closed, but would you be able to answer my q like I'm 5 please? 😄  Will this not happen anywhere else?

**Comment by DhanyaHerath** [comment]
Still getting it on demo server :((
<img width="1034" alt="image" src="https://github.com/openmsupply/open-msupply/assets/29744386/5218c9a8-aae8-4e52-b906-e134f2409669">

**Comment by roxy-dao** [comment]
> @roxy-dao happy for this issue to be closed, but would you be able to answer my q like I'm 5 please? 😄 Will this not happen anywhere else?

The user would always require `query patient` permission to search for patients in prescription page... so yes they will always need this permission. So yup, have to have this permission on every time we initialise the demo... 

Yeah... I don't see the permission on in demo server either 🤔
